server:
  port: ${REVIEW_PORT}

spring:
  application:
    name: review

  #MongoDB connection
  data:
    mongodb:
      host: localhost
      port: 27017
      authentication-database: admin
      database: ${MONGO_REVIEW_DATABASE}
      username: ${MONGO_INITDB_ROOT_USERNAME}
      password: ${MONGO_INITDB_ROOT_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MongoDBDialect
        format_sql: true
    show-sql: true

  #Kafka
  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      group-id: ${KAFKA_REVIEW_GROUP}
    topic:
      review: ${KAFKA_DELETE_REVIEW_TOPIC}

#Zipkin
management:
  tracing:
    sampling:
      probability: 1.0

  #Actuator Prometheus Endpoint
  endpoints:
    web:
      exposure:
        include: prometheus
  prometheus:
    metrics:
      export:
        enabled: true
  metrics:
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true

#Eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true