server:
  port: ${REVIEW_PORT}

spring:
  application:
    name: review

  #Redis
  cache:
    type: redis
    cache-names: redis-cache
  data:
    redis:
      host: ${REDIS_HOST}
      port: 6379
      password: ${REDIS_PASSWORD}

    #MongoDB connection
    mongodb:
      host: ${MONGO_HOST}
      port: 27017
      authentication-database: admin
      database: ${MONGO_REVIEW_DATABASE}
      username: ${MONGO_INITDB_ROOT_USERNAME}
      password: ${MONGO_INITDB_ROOT_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MongoDBDialect
        format_sql: true
    show-sql: true

#Zipkin
management:
  tracing:
    sampling:
      probability: 1.0

#Eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true