server:
  port: 8080

spring:
  application:
    name: customer
  datasource:
    username: oleg
    password: password
    url: jdbc:postgresql://localhost:5432/customer?currentSchema=customer
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

  liquibase:
    change-log: classpath:liquibase/db.changelog.yaml
    enabled: true