openapi:
  info:
    title: Customer API
    version: 1.0.0
    description: |
      Welcome to the Customer Service API! This API provides endpoints for managing customer data,
      including retrieving customer details, updating customer information, accessing customer reviews,
      and purchase history, processing purchases, and deleting customer accounts.

      User authentication is required to access these endpoints. Please ensure you have appropriate
      authentication credentials before making requests.

      Explore the comprehensive documentation to understand the functionality and usage of each endpoint.

      _**Note:** some endpoints are intended for Feign clients and may not be accessible to regular API consumers._

      For detailed instructions on running the project locally and contributing, visit the GitHub repository.
      - [GitHub Repository](https://github.com/OlegRyazancev/online-shop/tree/master/customer) - Access the GitHub
      repository for the source code, detailed README, and instructions for running the application.
    contact:
      name: Oleg Ryazancev
      email: oleg.ryazancev1022@gmail.com