openapi:
  info:
    title: Purchase API
    version: 1.0.0
    description: |
      Welcome to the Purchase Service API! This API provides endpoints for processing purchases
      and retrieving purchase information for customers.

      This service operates independently and does not directly connect to the base API gateway.
      Communication with other services is handled via Feign clients.
      
      User authentication is required to access these endpoints. Please ensure you have appropriate
      authentication credentials before making requests.

      _**Note:** It is a **technical service**, but you can make some example requests._

      Explore the comprehensive documentation to understand the functionality and usage of each endpoint.

      For detailed instructions on running the project locally and contributing, visit the GitHub repository.
      - [GitHub Repository](https://github.com/OlegRyazancev/online-shop/tree/master/purchase): Access the GitHub
      repository for the source code, detailed README, and instructions for running the application.
    contact:
      name: Oleg Ryazancev
      email: oleg.ryazancev1022@gmail.com