server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: customer
          uri: lb://CUSTOMER
          predicates:
            - Path=/api/v1/customers/**
          filters:
            - AuthenticationFilter

        - id: organization
          uri: lb://ORGANIZATION
          predicates:
            - Path=/api/v1/organizations/**
          filters:
            - AuthenticationFilter

        - id: product
          uri: lb://PRODUCT
          predicates:
            - Path=/api/v1/products/**
          filters:
            - AuthenticationFilter

        - id: auth
          uri: lb://AUTH
          predicates:
            - Path=/api/v1/auth/**

        - id: admin
          uri: lb://ADMIN
          predicates:
            - Path=/api/v1/admin/**
          filters:
            - AuthenticationFilter

  security:
    jwt:
      secret: ${JWT_SECRET}

#Zipkin
management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans

  #Actuator Prometheus Endpoint
  endpoints:
    web:
      exposure:
        include: prometheus
  prometheus:
    metrics:
      export:
        enabled: true
  metrics:
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true

#Eureka
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
      fetch-registry: true
      register-with-eureka: true
  instance:
    preferIpAddress: true