server:
  port: 8080
  servlet:
    context-path: /

spring:
  config:
    import: classpath:openapi/openapi-config.yml
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: customer
          uri: lb://CUSTOMER
          predicates:
            - Path=/api/v1/customers/**
          filters:
            - AuthenticationFilter

        - id: organization
          uri: lb://ORGANIZATION
          predicates:
            - Path=/api/v1/organizations/**
          filters:
            - AuthenticationFilter

        - id: product
          uri: lb://PRODUCT
          predicates:
            - Path=/api/v1/products/**
          filters:
            - AuthenticationFilter

        - id: auth
          uri: lb://AUTH
          predicates:
            - Path=/api/v1/auth/**

        - id: admin
          uri: lb://ADMIN
          predicates:
            - Path=/api/v1/admin/**
          filters:
            - AuthenticationFilter

  security:
    jwt:
      secret: ${JWT_SECRET}

#Zipkin
management:
  tracing:
    sampling:
      probability: 1.0

  #Actuator Prometheus Endpoint
  endpoints:
    web:
      exposure:
        include: prometheus
  prometheus:
    metrics:
      export:
        enabled: true
  metrics:
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true

#Eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
      fetch-registry: true
      register-with-eureka: true
  instance:
    preferIpAddress: true

#OpenAPI
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    urls:
      - url: /v3/api-docs
        name: API Gateway Service

      - url: /v3/api-docs/auth
        name: Auth Service

      - url: /v3/api-docs/customer
        name: Customer Service

      - url: /v3/api-docs/organization
        name: Organization Service

      - url: /v3/api-docs/product
        name: Product Service

      - url: /v3/api-docs/admin
        name: Admin Service

      - url: /v3/api-docs/purchase
        name: Purchase Service

      - url: /v3/api-docs/review
        name: Review Service

      - url: /v3/api-docs/logo
        name: Logo Service

      - url: /v3/api-docs/mail
        name: Mail Service
