server:
  port: ${API_GATEWAY_PORT}

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: customer
          uri: lb://CUSTOMER
          predicates:
            - Path=/api/v1/customers/**
          filters:
            - AuthenticationFilter

        - id: organization
          uri: lb://ORGANIZATION
          predicates:
            - Path=/api/v1/organizations/**
          filters:
            - AuthenticationFilter

        - id: product
          uri: lb://PRODUCT
          predicates:
            - Path=/api/v1/products/**
          filters:
            - AuthenticationFilter

        - id: auth
          uri: lb://AUTH
          predicates:
            - Path=/api/v1/auth/**

  security:
    jwt:
      secret: ${JWT_SECRET}

management:
  tracing:
    sampling:
      probability: 1.0

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
      fetch-registry: true
      register-with-eureka: true
  instance:
    preferIpAddress: true