server:
  port: ${PRODUCT_PORT}

spring:
  application:
    name: product

  #MariaDB connection
  datasource:
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    url: jdbc:mariadb://${MYSQL_HOST}:3306/${MYSQL_PRODUCT_DATABASE}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        format_sql: true
    show-sql: true

  #Kafka
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    consumer:
      group-id: ${KAFKA_PRODUCT_GROUP}
    topic:
      admin: ${KAFKA_REQUESTS_ADMIN_TOPIC}
      product:
        register: ${KAFKA_REGISTER_PRODUCT_TOPIC}
        update: ${KAFKA_UPDATE_PRODUCT_TOPIC}

  #Liquibase
  liquibase:
    change-log: classpath:liquibase/db.changelog.yml
    enabled: true

#Zipkin
management:
  tracing:
    sampling:
      probability: 1.0

#Eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true