server:
  port: ${PRODUCT_PORT}
  servlet:
    context-path: /

spring:
  profiles:
    active: default
  config:
    import: classpath:openapi/open-api-config.yml,
      optional:file:.env[.properties]
  messages:
    always-use-message-format: false
    fallback-to-system-locale: true
    encoding: UTF-8
    basename: messages/messages
  application:
    name: product

  #MariaDB connection
  datasource:
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    url: jdbc:mariadb://localhost:3306/${MYSQL_PRODUCT_DATABASE}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        format_sql: true
    show-sql: true

  #Redis
  cache:
    type: redis
    cache-names: redis-cache
  data:
    redis:
      host: localhost
      port: 6379
      password: ${REDIS_PASSWORD}


  #Kafka
  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      group-id: ${KAFKA_PRODUCT_GROUP}
    topic:
      admin: ${KAFKA_REQUESTS_ADMIN_TOPIC}
      review: ${KAFKA_DELETE_REVIEW_TOPIC}
      product:
        register: ${KAFKA_REGISTER_PRODUCT_TOPIC}
        update: ${KAFKA_UPDATE_PRODUCT_TOPIC}
        delete: ${KAFKA_DELETE_PRODUCT_TOPIC}
        change-status: ${KAFKA_CHANGE_STATUS_PRODUCT_TOPIC}
      mail: ${KAFKA_MAIL_TOPIC}

  #Liquibase
  liquibase:
    change-log: classpath:liquibase/db.changelog.yml
    enabled: true

#Zipkin
management:
  tracing:
    sampling:
      probability: 1.0

  #Actuator Endpoint
  endpoints:
    web:
      exposure:
        include: "*"
  prometheus:
    metrics:
      export:
        enabled: true
  metrics:
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true
  endpoint:
    health:
      show-details: always
  health:
    circuitbreakers:
      enabled: true

#Resilience4j
resilience4j:
  circuitbreaker:
    instances:
      product:
        sliding-window-type: COUNT_BASED
        failure-rate-threshold: 50
        minimum-number-of-calls: 5
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state: 5s
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-size: 10
        register-health-indicator: true

#Eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true

#OpenApi
openapi:
  service:
    url: http://localhost:8080
springdoc:
  api-docs:
    path: /v3/api-docs/product
  swagger-ui:
    path: /swagger-ui.html/product