server:
  port: ${PURCHASE_PORT}

spring:
  application:
    name: purchase

  #MongoDB connection
  data:
    mongodb:
      host: ${MONGO_HOST}
      port: 27017
      authentication-database: admin
      database: ${MONGO_PURCHASE_DATABASE}
      username: ${MONGO_INITDB_ROOT_USERNAME}
      password: ${MONGO_INITDB_ROOT_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MongoDBDialect
        format_sql: true
    show-sql: true
  #Kafka
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    topic:
      customer: ${KAFKA_CUSTOMER_TOPIC}
      product: ${KAFKA_PRODUCT_TOPIC}

#Zipkin
management:
  tracing:
    sampling:
      probability: 1.0

#Eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true