server:
  port: ${PURCHASE_PORT}

spring:
  application:
    name: purchase

  #MongoDB connection
  data:
    mongodb:
      host: mongodb
      port: 27017
      authentication-database: admin
      database: ${MONGO_PURCHASE_DATABASE}
      username: ${MONGO_INITDB_ROOT_USERNAME}
      password: ${MONGO_INITDB_ROOT_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MongoDBDialect
        format_sql: true
    show-sql: true
  #Kafka
  kafka:
    bootstrap-servers: kafka:9092
    topic:
      customer:
        update: ${KAFKA_UPDATE_CUSTOMER_TOPIC}
      product:
        update: ${KAFKA_UPDATE_PRODUCT_TOPIC}

#Zipkin
management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans

  #Actuator Prometheus Endpoint
  endpoints:
    web:
      exposure:
        include: prometheus
  prometheus:
    metrics:
      export:
        enabled: true
  metrics:
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true

#Eureka
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
    fetch-registry: true
    register-with-eureka: true