server:
  port: ${PURCHASE_PORT}
  servlet:
    context-path: /

spring:
  config:
    import: classpath:openapi/open-api-config.yml
  application:
    name: purchase

  #MongoDB connection
  data:
    mongodb:
      host: localhost
      port: 27017
      authentication-database: admin
      database: ${MONGO_PURCHASE_DATABASE}
      username: ${MONGO_INITDB_ROOT_USERNAME}
      password: ${MONGO_INITDB_ROOT_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MongoDBDialect
        format_sql: true
    show-sql: true
  #Kafka
  kafka:
    bootstrap-servers: localhost:29092
    topic:
      customer:
        update: ${KAFKA_UPDATE_CUSTOMER_TOPIC}
      product:
        update: ${KAFKA_UPDATE_PRODUCT_TOPIC}

#Zipkin
management:
  tracing:
    sampling:
      probability: 1.0

  #Actuator Prometheus Endpoint
  endpoints:
    web:
      exposure:
        include: prometheus
  prometheus:
    metrics:
      export:
        enabled: true
  metrics:
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true

#Eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true

#OpenApi
openapi:
  service:
    url: http://localhost:${PURCHASE_PORT}
springdoc:
  api-docs:
    path: /v3/api-docs/purchase
  swagger-ui:
    path: /swagger-ui.html/purchase