server:
  port: 8083

spring:
  application:
    name: purchase

  data:
    mongodb:
      host: localhost
      port: 27017
      authentication-database: admin
      database: purchase-history
      username: oleg
      password: password
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MongoDBDialect
        format_sql: true
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
      fetch-registry: true
      register-with-eureka: true
  instance:
    preferIpAddress: true