server:
  port: ${NOTIFICATION_PORT}
  servlet:
    context-path: /

logging:
  level:
    com.ryazancev.notification.kafka.NotificationMessageListener: debug
    com.ryazancev.notification.util.exception.NotificationExceptionHandler: debug

spring:
  config:
    import: classpath:openapi/open-api-config.yml
  messages:
    always-use-message-format: false
    fallback-to-system-locale: true
    encoding: UTF-8
    basename: messages/messages
  application:
    name: notification

  mail: ${MAIL_USERNAME}

  #MongoDB connection
  data:
    mongodb:
      host: mongodb
      port: 27017
      authentication-database: admin
      database: ${MONGO_NOTIFICATION_DATABASE}
      username: ${MONGO_INITDB_ROOT_USERNAME}
      password: ${MONGO_INITDB_ROOT_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MongoDBDialect
        format_sql: true
    show-sql: true

  #Kafka
  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: ${KAFKA_NOTIFICATION_GROUP}
    topic: ${KAFKA_NOTIFICATION_TOPIC}

#Zipkin
management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans

  #Actuator Endpoint
  endpoints:
    web:
      exposure:
        include: "*"
  prometheus:
    metrics:
      export:
        enabled: true
  metrics:
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true
  endpoint:
    health:
      show-details: always
  health:
    circuitbreakers:
      enabled: true

#Resilience4j
resilience4j:
  circuitbreaker:
    instances:
      notification:
        sliding-window-type: COUNT_BASED
        failure-rate-threshold: 50
        minimum-number-of-calls: 5
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state: 5s
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-size: 10
        register-health-indicator: true

#Eureka
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
    fetch-registry: true
    register-with-eureka: true

#OpenApi
openapi:
  service:
    url: http://localhost:${NOTIFICATION_PORT}
springdoc:
  api-docs:
    path: /v3/api-docs/notification
  swagger-ui:
    path: /swagger-ui.html/notification

