server:
  port: ${NOTIFICATION_PORT}
  servlet:
    context-path: /

spring:
  profiles:
    active: default
  config:
    import: optional:file:.env[.properties]
  application:
    name: notification
  mail: ${MAIL_USERNAME}

  #MongoDB connection
  data:
    mongodb:
      host: localhost
      port: 27017
      authentication-database: admin
      database: ${MONGO_PURCHASE_DATABASE}
      username: ${MONGO_INITDB_ROOT_USERNAME}
      password: ${MONGO_INITDB_ROOT_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MongoDBDialect
        format_sql: true
    show-sql: true

  #Kafka
  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      group-id: ${KAFKA_NOTIFICATION_GROUP}
    topic: ${KAFKA_NOTIFICATION_TOPIC}

#Zipkin
management:
  tracing:
    sampling:
      probability: 1.0

  #Actuator Endpoint
  endpoints:
    web:
      exposure:
        include: "*"
  prometheus:
    metrics:
      export:
        enabled: true
  metrics:
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true
  endpoint:
    health:
      show-details: always
  health:
    circuitbreakers:
      enabled: true

#Resilience4j
resilience4j:
  circuitbreaker:
    instances:
      product:
        sliding-window-type: COUNT_BASED
        failure-rate-threshold: 50
        minimum-number-of-calls: 5
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state: 5s
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-size: 10
        register-health-indicator: true

#Eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true