global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'admin'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'admin:8089' ]
        labels:
          application: 'Admin Service Application'

  - job_name: 'auth'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'auth:9091' ]
        labels:
          application: 'Auth Service Application'

  - job_name: 'customer'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'customer:8082' ]
        labels:
          application: 'Customer Service Application'

  - job_name: 'logo'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'logo:8087' ]
        labels:
          application: 'Logo Service Application'

  - job_name: 'mail'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'mail:8088' ]
        labels:
          application: 'Mail Service Application'

  - job_name: 'organization'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'organization:8085' ]
        labels:
          application: 'Organization Service Application'

  - job_name: 'product'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'product:8084' ]
        labels:
          application: 'Product Service Application'

  - job_name: 'purchase'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'purchase:8083' ]
        labels:
          application: 'Purchase Service Application'

  - job_name: 'review'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'review:8086' ]
        labels:
          application: 'Review Service Application'

  - job_name: 'notification'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'notification:9092' ]
        labels:
          application: 'Notification Service Application'
