server:
  port: ${LOGO_PORT}

spring:
  application:
    name: logo


#Zipkin
management:
  tracing:
    sampling:
      probability: 1.0

  #Actuator Prometheus Endpoint
  endpoints:
    web:
      exposure:
        include: prometheus
  prometheus:
    metrics:
      export:
        enabled: true
  metrics:
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true

#Eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true

#Minio
minio:
  bucket: ${MINIO_BUCKET}
  url: http://localhost:9000
  accessKey: ${MINIO_ACCESS_KEY}
  secretKey: ${MINIO_SECRET_KEY}

