server:
  port: ${MAIL_PORT}

spring:
  application:
    name: mail

  #Kafka
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    consumer:
      group-id: ${KAFKA_MAIL_GROUP}
    topic: ${KAFKA_MAIL_TOPIC}

  #Mail
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_HOST_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        debug: false
        transport:
          protocol: smtp
        smtp:
          auth: true
          starttls:
            enable: true

#Zipkin
management:
  tracing:
    sampling:
      probability: 1.0

  #Actuator Prometheus Endpoint
  endpoints:
    web:
      exposure:
        include: prometheus

#Eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
