server:
  port: ${MAIL_PORT}
  servlet:
    context-path: /

spring:
  profiles:
    active: default
  config:
    import: classpath:openapi/open-api-config.yml
  application:
    name: mail

  #Kafka
  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      group-id: ${KAFKA_MAIL_GROUP}
    topic: ${KAFKA_MAIL_TOPIC}

  #Mail
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_HOST_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        debug: false
        transport:
          protocol: smtp
        smtp:
          auth: true
          starttls:
            enable: true

#Zipkin
management:
  tracing:
    sampling:
      probability: 1.0

  #Actuator Prometheus Endpoint
  endpoints:
    web:
      exposure:
        include: prometheus
  prometheus:
    metrics:
      export:
        enabled: true
  metrics:
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true

#Eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true

#OpenApi
openapi:
  service:
    url: http://localhost:${MAIL_PORT}
springdoc:
  api-docs:
    path: /v3/api-docs/mail
  swagger-ui:
    path: /swagger-ui.html/mail

