openapi:
  info:
    title: Purchase API
    version: 1.0.0
    description: |
      Welcome to the Mail Service API! This API provides asynchronous communication 
      for sending different types of emails using Kafka messaging.

      The Mail Service facilitates the delivery of various email types, including 
      notifications, alerts, and user communications. It operates asynchronously, 
      allowing for efficient and scalable email delivery.
    
      _**Note:** It is a **technical service**._

      Explore the comprehensive documentation to understand the functionality 
      and usage of each endpoint.

      For detailed instructions on running the project locally and contributing, 
      visit the GitHub repository.
      - [GitHub Repository](https://github.com/OlegRyazancev/online-shop/tree/master/mail): 
      Access the GitHub repository for the source code, detailed README, 
      and instructions for running the application.
    contact:
      name: Oleg Ryazancev
      email: oleg.ryazancev1022@gmail.com