INSERT INTO users (name, email, password, customer_id, locked, confirmed)
VALUES ('John Doe',
        'john@example.com',
        '$2a$10$K/UVr4zg0OY6BE6OyxOh3.zEonNHc4jfwrxabu4RpUUTmeCzQDaH2',
        1,
        false,
        true),

       ('Jane Smith',
        'jane@example.com',
        '$2a$10$K/UVr4zg0OY6BE6OyxOh3.zEonNHc4jfwrxabu4RpUUTmeCzQDaH2',
        2,
        true,
        true),

       ('Bob Johnson',
        'bob@example.com',
        '$2a$10$K/UVr4zg0OY6BE6OyxOh3.zEonNHc4jfwrxabu4RpUUTmeCzQDaH2',
        3,
        false,
        true),

       ('Alice Brown',
        'alice@example.com',
        '$2a$10$K/UVr4zg0OY6BE6OyxOh3.zEonNHc4jfwrxabu4RpUUTmeCzQDaH2',
        4,
        false,
        true),

       ('Charlie Wilson',
        'charlie@example.com',
        '$2a$10$K/UVr4zg0OY6BE6OyxOh3.zEonNHc4jfwrxabu4RpUUTmeCzQDaH2',
        5,
        false,
        true);