package com.ryazancev.dto.mail;

public enum MailType {

    USER_REGISTRATION,
    MAIL_CONFIRMATION,

    ORGANIZATION_REGISTRATION_ACCEPTED,
    ORGANIZATION_REGISTRATION_REJECTED,

    PRODUCT_REGISTRATION_ACCEPTED,
    PRODUCT_REGISTRATION_REJECTED
}
