server:
  port: 9091
  servlet:
    context-path: /

spring:
  application:
    name: auth

  #Kafka
  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: ${KAFKA_AUTH_GROUP}
    topic:
      mail: ${KAFKA_MAIL_TOPIC}
      user:
        toggle-lock: ${KAFKA_TOGGLE_LOCK_USER_TOPIC}
        delete: ${KAFKA_DELETE_USER_TOPIC}

  #MariaDB connection
  datasource:
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    url: jdbc:mariadb://mariadb:3306/${MYSQL_AUTH_DATABASE}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        format_sql: true
    show-sql: true
  #Liquibase
  liquibase:
    change-log: classpath:liquibase/db.changelog.yml
    enabled: true

security:
  jwt:
    access: ${JWT_ACCESS}
    refresh: ${JWT_REFRESH}
    secret: ${JWT_SECRET}
    confirmation_link_prefix: ${SECURITY_CONFIRMATION_LINK_PREFIX_DOCKER}

#Zipkin
management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans

  #Actuator Prometheus Endpoint
  endpoints:
    web:
      exposure:
        include: prometheus
  prometheus:
    metrics:
      export:
        enabled: true
  metrics:
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true


#Eureka
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
    fetch-registry: true
    register-with-eureka: true

#OpenApi
openapi:
  service:
    title: Auth-Service Documentation
    version: 1.0.0
    url: http://api-gateway:8080
springdoc:
  api-docs:
    path: /v3/api-docs/auth
  swagger-ui:
    path: /swagger-ui.html/auth