server:
  port: 8089
  servlet:
    context-path: /

spring:
  profiles:
    active: docker
  config:
    import: classpath:openapi/open-api-config.yml
  application:
    name: admin

  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: ${KAFKA_ADMIN_GROUP}
    topic:
      admin: ${KAFKA_REQUESTS_ADMIN_TOPIC}
      user:
        toggle-lock: ${KAFKA_TOGGLE_LOCK_USER_TOPIC}
      organization:
        register: ${KAFKA_REGISTER_ORGANIZATION_TOPIC}
        change-status: ${KAFKA_CHANGE_STATUS_ORGANIZATION_TOPIC}
      product:
        register: ${KAFKA_REGISTER_PRODUCT_TOPIC}
        change-status: ${KAFKA_CHANGE_STATUS_PRODUCT_TOPIC}


  #PostgreSQL connection
  datasource:
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    url: jdbc:postgresql://postgres:5432/${POSTGRES_ADMIN_DATABASE}?currentSchema=${POSTGRES_ADMIN_SCHEMA}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

  #Redis
  cache:
    type: redis
    cache-names: redis-cache
  data:
    redis:
      host: redis
      port: 6379
      password: ${REDIS_PASSWORD}

  #Liquibase
  liquibase:
    change-log: classpath:liquibase/db.changelog.yaml
    enabled: true

#Zipkin
management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans

  #Actuator Prometheus Endpoint
  endpoints:
    web:
      exposure:
        include: prometheus
  prometheus:
    metrics:
      export:
        enabled: true
  metrics:
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true

#Eureka
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
    fetch-registry: true
    register-with-eureka: true

#OpenApi
openapi:
  service:
    url: http://api-gateway:8080
springdoc:
  api-docs:
    path: /v3/api-docs/admin
  swagger-ui:
    path: /swagger-ui.html/admin
