server:
  port: ${ADMIN_PORT}

spring:
  application:
    name: admin


#Zipkin
management:
  tracing:
    sampling:
      probability: 1.0

#Eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
