spring:
  application:
    name: eureka-server

server:
  port: 8761

#Zipkin
management:
  tracing:
    sampling:
      probability: 1.0

  #Actuator Endpoint
  endpoints:
    web:
      exposure:
        include: prometheus
  prometheus:
    metrics:
      export:
        enabled: true
  metrics:
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true

#Eureka
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
