spring:
  application:
    name: eureka-server

server:
  port: 8761

#Zipkin
management:
  tracing:
    sampling:
      probability: 1.0

  #Actuator Prometheus Endpoint
  endpoints:
    web:
      exposure:
        include: prometheus

#Eureka
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
