spring:
  application:
    name: eureka-server

server:
  port: 8761

management:
  tracing:
    sampling:
      probability: 1.0

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
