openapi:
  info:
    title: Auth API
    version: 1.0.0
    description: |
      Welcome to the Authentication Service API! This API provides endpoints for user authentication,
      registration, token refresh, and email confirmation.
  
      Utilize these endpoints to manage user authentication within your application securely.
      Explore the comprehensive documentation to understand the functionality and usage of each endpoint.
  
      Note that authentication is not required to access this API.
  
      For detailed instructions on running the project locally and contributing, visit the GitHub repository.
  
      - [GitHub Repository](https://github.com/OlegRyazancev/online-shop/tree/master/auth) - Access the GitHub
      repository for the source code, detailed README, and instructions for running the application.
    contact:
      name: Oleg Ryazancev
      email: oleg.ryazancev1022@gmail.com